# Default playbook.
#
# Should configure a development setup to the point where a server or
# equivalent can be started with a single command.
#
# For Django projects, this means configured to a point where all there's left
# to do after running `vagrant ssh`, is running: `python manage.py runserver`.

---

- hosts: all

  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: Update apt cache (if old)
      apt: update_cache=yes cache_valid_time=84600

  roles:
  - vim

...
