# Test playbook.
#
# Should configure a test setup to the point where tests can be started with a
# single command.
#
# For Django projects, this means configured to a point where all there's left
# to do after running `vagrant ssh`, is running: `python manage.py test`.

---
# Run the entire default setup playbook
- include: default.yml

# Run production specific playbook
- hosts: all

  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root

  roles:
  - vim

...
